# Generated by Django 5.2.17 on 2026-08-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("skill", "Skill"),
                            ("experience", "Experience"),
                            ("achievement", "Achievement"),
                            ("blog", "Blog"),
                        ],
                        db_index=True,
                        default="project",
                        max_length=50,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "icon",
                    models.CharField(blank=True, default="fas fa-tag", max_length=100),
                ),
                (
                    "color",
                    models.CharField(blank=True, default="#38bdf8", max_length=50),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
    ]
