# Generated by Django 5.2.7 on 2026-08-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='live_url',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(db_index=True, default='Web Application', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='completed_date',
            field=models.CharField(blank=True, help_text='e.g. 2025-05-15', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.TextField(blank=True, help_text='Cover screenshot image URL', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Detailed project technical documentation, architecture, and markdown'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('OFFLINE', 'Offline'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], db_index=True, default='LIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags', max_length=255),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['website', 'status'], name='idx_proj_site_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['website', 'category'], name='idx_proj_site_cat'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['website', 'visible'], name='idx_proj_site_vis'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['website', 'created_at'], name='idx_proj_site_created'),
        ),
    ]
