# Generated by Django 5.2.17 on 2026-08-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_remove_project_live_url_project_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="project",
            name="category_id_val",
            field=models.IntegerField(
                blank=True, help_text="Optional Taxonomy Category ID", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="documentation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Full case study & architecture breakdown in Markdown/HTML",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="live_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="project_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short display name e.g. CardFlow",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=models.TextField(
                blank=True, help_text="Cover thumbnail URL or media path", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Short summary pitch"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.TextField(
                blank=True,
                help_text="Cover screenshot / thumbnail image URL",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pilot", "Pilot"),
                    ("completed", "Completed"),
                    ("draft", "Draft"),
                    ("archived", "Archived"),
                    ("LIVE", "Live"),
                    ("OFFLINE", "Offline"),
                    ("PLANNED", "Planned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated tags e.g. Python, React, PostgreSQL",
                max_length=350,
            ),
        ),
        migrations.CreateModel(
            name="ProjectScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.TextField(help_text="Screenshot URL or media path")),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
