# Generated by Django 5.2.7 on 2026-08-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='e.g. dev-meet, dev-mitra, dev-mate', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('badge', models.CharField(help_text='e.g. MEET, MITRA, MATE', max_length=20)),
                ('tag', models.CharField(help_text='Description or tagline', max_length=255)),
                ('primary_color', models.CharField(default='blue', help_text='blue, sky, or violet', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
