# Generated by Django 5.2.7 on 2026-08-22 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.CharField(db_index=True, default='Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='experience',
            name='period',
            field=models.CharField(blank=True, help_text='e.g. 2022 - Present', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='status',
            field=models.CharField(choices=[('CURRENT', 'Current Role'), ('PAST', 'Past Experience')], db_index=True, default='CURRENT', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['website', 'status'], name='idx_exp_site_status'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['website', 'category'], name='idx_exp_site_cat'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['website', 'visible'], name='idx_exp_site_vis'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['website', 'created_at'], name='idx_exp_site_created'),
        ),
    ]
