# Generated by Django 5.2.17 on 2026-08-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experiences", "0002_alter_experience_options_experience_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="experience",
            name="category_id_val",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="company_logo",
            field=models.TextField(
                blank=True, help_text="Company logo URL or media path", null=True
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="company_website",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="currently_working",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="employment_type",
            field=models.CharField(default="full-time", max_length=50),
        ),
        migrations.AddField(
            model_name="experience",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="experience",
            name="short_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company",
            field=models.CharField(help_text="Company name", max_length=150),
        ),
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed key responsibilities and highlights",
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="location",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="role",
            field=models.CharField(help_text="Job title or position", max_length=150),
        ),
        migrations.CreateModel(
            name="ExperienceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.TextField(help_text="Workplace photo URL or media path"),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="experiences.experience",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
