# Generated by Django 5.2.7 on 2026-08-22 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Roshan Kumar', max_length=150)),
                ('title', models.CharField(default='Senior Full Stack Developer & UI Architect', max_length=200)),
                ('bio', models.TextField(default='Passionate software engineer building high-performance React web applications, scalable Node.js microservices, and elegant OLED dark glassmorphic user interfaces with seamless UX.')),
                ('location', models.CharField(default='New Delhi, India', max_length=150)),
                ('email', models.EmailField(default='roshan.dev@example.com', max_length=254)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('experience_years', models.CharField(default='5+ Years', max_length=50)),
                ('github', models.URLField(blank=True, default='https://github.com/roshan-dev', max_length=300)),
                ('linkedin', models.URLField(blank=True, default='https://linkedin.com/in/roshan-dev', max_length=300)),
                ('twitter', models.CharField(blank=True, default='@roshan_dev', max_length=100)),
                ('website_url', models.URLField(blank=True, default='https://roshankumar.dev', max_length=300)),
                ('resume_url', models.URLField(blank=True, default='https://roshankumar.dev/resume.pdf', max_length=500)),
                ('avatar', models.TextField(default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='websites.website')),
            ],
        ),
    ]
