# Generated by Django 5.2.17 on 2026-08-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolioprofile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="portfolioprofile",
            name="resume_url",
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="available_for_freelance",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="cover_letter",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="full_name",
            field=models.CharField(default="Roshan Damor", max_length=150),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_badge",
            field=models.CharField(default="Hello, I am", max_length=100),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_description",
            field=models.TextField(
                default="I build production software and AI-powered applications, from backend systems and SaaS platforms to LLM-powered workflows and intelligent developer tools."
            ),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_image",
            field=models.TextField(blank=True, default="/media/hero/custom_hero.webp"),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_stat_1_icon",
            field=models.CharField(default="fas fa-users", max_length=50),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_stat_1_label",
            field=models.CharField(default="Production Users", max_length=100),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_stat_1_value",
            field=models.CharField(default="1,000+", max_length=50),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_stat_2_icon",
            field=models.CharField(default="fas fa-id-card", max_length=50),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_stat_2_label",
            field=models.CharField(default="ID Cards Processed", max_length=100),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_stat_2_value",
            field=models.CharField(default="136K+", max_length=50),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_stat_3_icon",
            field=models.CharField(default="fas fa-cloud-download-alt", max_length=50),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_stat_3_label",
            field=models.CharField(default="Cards Downloaded", max_length=100),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hero_stat_3_value",
            field=models.CharField(default="86K+", max_length=50),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="hourly_rate",
            field=models.CharField(default="45.00", max_length=50),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="instagram",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="open_to_opportunities",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="profile_image",
            field=models.TextField(blank=True, default="/media/profile/hero.webp"),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="resume",
            field=models.TextField(
                blank=True,
                default="/media/documents/Roshan_Damor_Resume.pdf",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="status",
            field=models.CharField(default="available", max_length=50),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="video_resume",
            field=models.URLField(
                blank=True,
                default="https://www.youtube.com/@logicbyroshan",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="work_type",
            field=models.CharField(default="remote", max_length=50),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="youtube",
            field=models.URLField(
                blank=True, default="https://youtube.com/@logicbyroshan", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="avatar",
            field=models.TextField(
                blank=True,
                default="https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="bio",
            field=models.TextField(
                default="Software Engineer specializing in scalable full-stack web applications and AI workflows."
            ),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="email",
            field=models.EmailField(default="mail@logicbyroshan.in", max_length=254),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="experience_years",
            field=models.CharField(default="3", max_length=50),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="github",
            field=models.URLField(
                blank=True, default="https://github.com/logicbyroshan", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="linkedin",
            field=models.URLField(
                blank=True,
                default="https://linkedin.com/in/logicbyroshan",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="location",
            field=models.CharField(
                default="Bhopal, Madhya Pradesh, India", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="phone",
            field=models.CharField(default="+91 90000 00000", max_length=50),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="title",
            field=models.CharField(
                default="Software Engineer · Full Stack AI", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="twitter",
            field=models.CharField(
                blank=True, default="https://twitter.com/logicbyroshan", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="portfolioprofile",
            name="website_url",
            field=models.URLField(
                blank=True, default="https://logicbyroshan.in", max_length=300
            ),
        ),
    ]
