# Generated by Django 5.2.7 on 2026-08-16 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('tag', models.CharField(choices=[('Inquiry', 'Inquiry'), ('Hire', 'Hire'), ('Feedback', 'Feedback'), ('Consultation', 'Consultation')], default='Inquiry', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='websites.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
