# Generated by Django 5.2.7 on 2026-08-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='reply_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='starred',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='subject',
            field=models.CharField(blank=True, default='General Inquiry', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='tag',
            field=models.CharField(choices=[('Inquiry', 'Inquiry'), ('Hire', 'Hire'), ('Feedback', 'Feedback'), ('Consultation', 'Consultation')], db_index=True, default='Inquiry', max_length=50),
        ),
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['website', 'is_read'], name='idx_msg_site_read'),
        ),
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['website', 'tag'], name='idx_msg_site_tag'),
        ),
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['website', 'starred'], name='idx_msg_site_starred'),
        ),
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['website', 'created_at'], name='idx_msg_site_created'),
        ),
    ]
