# Generated by Django 5.2.17 on 2026-08-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contactinquiry_replied_contactinquiry_replied_at_and_more"),
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinquiry",
            name="admin_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contactinquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("read", "Read"),
                    ("replied", "Replied"),
                    ("spam", "Spam"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="new",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="contactinquiry",
            index=models.Index(
                fields=["website", "status"], name="idx_msg_site_status"
            ),
        ),
    ]
