# Generated by Django 5.2.17 on 2026-08-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        db_index=True, default="Certification", max_length=100
                    ),
                ),
                ("issuer", models.CharField(blank=True, default="", max_length=150)),
                (
                    "date_earned",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 2024-11-20",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "credential_id",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "credential_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "badge_image",
                    models.TextField(
                        blank=True, help_text="Badge image URL or media path", null=True
                    ),
                ),
                (
                    "certificate_pdf",
                    models.TextField(
                        blank=True,
                        help_text="Certificate PDF URL or media path",
                        null=True,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["website", "is_active"], name="idx_ach_site_active"
                    ),
                    models.Index(
                        fields=["website", "category"], name="idx_ach_site_cat"
                    ),
                ],
            },
        ),
    ]
