# Generated by Django 5.2.7 on 2026-08-22 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(db_index=True, default='General', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='websites.website')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['website', 'category'], name='idx_faq_site_cat'), models.Index(fields=['website', 'visible'], name='idx_faq_site_vis'), models.Index(fields=['website', 'created_at'], name='idx_faq_site_created')],
            },
        ),
    ]
