# Generated by Django 5.2.7 on 2026-08-16 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FRONTEND', 'Frontend Development'), ('BACKEND', 'Backend Development'), ('DATABASE', 'Databases & Storage'), ('DEVOPS', 'DevOps & Tools'), ('OTHER', 'Other Technical Skills')], default='FRONTEND', max_length=20)),
                ('proficiency_percentage', models.PositiveIntegerField(default=85)),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='websites.website')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
