# Generated by Django 5.2.7 on 2026-08-22 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency_percentage',
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.PositiveIntegerField(default=85, help_text='Percentage 0-100'),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(db_index=True, default='Frontend', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Lucide icon name (e.g. Code2, Layers, Server, Database)', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['website', 'category'], name='idx_skill_site_cat'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['website', 'visible'], name='idx_skill_site_vis'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['website', 'created_at'], name='idx_skill_site_created'),
        ),
    ]
