# Generated by Django 5.2.17 on 2026-08-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "skills",
            "0002_remove_skill_proficiency_percentage_skill_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["order", "category", "name"]},
        ),
        migrations.AddField(
            model_name="skill",
            name="category_id_val",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="icon",
            field=models.CharField(
                blank=True,
                default="fas fa-code",
                help_text="FontAwesome or Lucide icon name",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="is_top",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="skill",
            name="proficiency",
            field=models.PositiveIntegerField(default=85, help_text="Percentage 0-100"),
        ),
        migrations.AddField(
            model_name="skill",
            name="years_of_experience",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="skill",
            name="icon_name",
            field=models.CharField(blank=True, default="Code2", max_length=100),
        ),
    ]
