# Generated by Django 5.2.7 on 2026-08-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(db_index=True, default='Software Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.CharField(blank=True, help_text='e.g. June 20, 2025', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(default='5 min read', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Full markdown article, code blocks, diagrams, benchmarks'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['website', 'status'], name='idx_blog_site_status'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['website', 'category'], name='idx_blog_site_cat'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['website', 'visible'], name='idx_blog_site_vis'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['website', 'created_at'], name='idx_blog_site_created'),
        ),
    ]
