# Generated by Django 5.2.17 on 2026-08-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_blogpost_category_blogpost_date_blogpost_read_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author_avatar",
            field=models.TextField(
                default="https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author_bio",
            field=models.TextField(
                default="Software Engineer specializing in scalable full-stack web applications and AI workflows."
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author_name",
            field=models.CharField(default="Roshan Damor", max_length=150),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author_role",
            field=models.CharField(
                default="Software Engineer · Full Stack AI", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.TextField(
                blank=True, help_text="Cover header image URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="sections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Sections with code snippets: [{'id': '...', 'heading': '...', 'content': '...', 'codeSnippet': {...}}]",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="subtitle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Executive subtitle / thesis statement",
                max_length=350,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of topic tags e.g. ['Microservices', 'System Design']",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tldr",
            field=models.TextField(
                blank=True, default="", help_text="TL;DR key takeaway bullet points"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="toc",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Table of Contents: [{'id': 'sec-1', 'title': 'Overview'}]",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Full markdown article, code blocks, diagrams",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="date",
            field=models.CharField(
                blank=True, help_text="e.g. November 15, 2024", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="summary",
            field=models.TextField(
                blank=True, default="", help_text="Short abstract / summary"
            ),
        ),
    ]
